#import "../preamble.typ": *

#lecture-date("10.09.2026")

#example[
  We recall the following basic homomorphisms:
  + Suppose $R$ is a ring. Then there exists a unique ring homomorphism
    $ epsilon : ZZ -> RR, space n |-> n dot 1_R. $

  + Suppose $FF$ is a field. Let $epsilon : ZZ -> FF$ be the ring homomorphism from the above, and let $I = ker epsilon$. Then $epsilon$ induces a monomorphism $ZZ \/ I -> FF$. In particular, $ZZ \/ I$ is an integral domain, therefore $I subset.eq ZZ$ is a prime ideal. Thus $I = {0}$ or $I = (p)$, for some $p in PP$. This "formalizes" our previous definition of $"char" FF$.
    + If $"char" FF = 0$, then $epsilon : ZZ -> FF$ is a monomorphism. In particular, $epsilon$ extends to a monomorphism $QQ -> FF$.
    + If $"char" FF = p in PP$, then $ran epsilon tilde.equiv ZZ \/ p ZZ tilde.equiv FF_p$.

  + Suppose we have a fixed homomorphism of rings $iota : R -> S$. Then for every choice of $theta in S$ there exists a unique ring homomorphism
    $ "ev"_theta : R[x] -> S $
    such that $"ev"_theta (r) = iota(r)$, for all $r in R$, and $"ev"_theta (x) = theta$, namely the evaluation map $p(x) |-> p(theta)$.
]

#definition[
  Let $FF$ be a field. A _(field) extension_ of $FF$ is a field $KK$ containing#footnote[Again, up to a monomorphism.] $FF$ as a subfield. We will also write $FF arrow.hook KK$ to denote this relationship.
]

#example[
  + $QQ arrow.hook RR$
  + $RR arrow.hook CC$
]

If $FF arrow.hook KK$ is a field extension, then $KK$ can be viewed as a vector space over $FF$.

#definition[
  The _degree_ of a field extension $FF arrow.hook KK$ is defined as the dimension of $KK$ as a vector space over $FF$. We also denote this as $[KK : FF]$ or $dim_FF KK$.
]

#example[
  + $[RR : QQ] = oo$
  + $[CC : RR] = 2$
]

#lemma[
  Suppose we have field extensions $FF arrow.hook KK arrow.hook LL$, then
  $ [LL : FF] = [LL : KK] dot [KK : FF]. $
]

#definition[
  Let $FF arrow.hook KK$ be a field extension and $alpha in KK$. We say that $alpha$ is _algebraic_ over $FF$ if there exists a non-zero polynomial $p(x) in FF[x]$ such that $p(alpha) = 0$. Otherwise $alpha$ is called _transcendental_ over $FF$.
]

#example[
  + $sqrt(2), sqrt(3)$ are algebraic over $QQ$.
  + $pi, e$ are transcendental over $QQ$.
]

#definition[
  We say that an extension $FF arrow.hook KK$ is _algebraic_, if every element $alpha in KK$ is algebraic over $FF$. Otherwise, we say that the extension is _transcendental_.
]

== Minimal polynomials

Suppose $FF arrow.hook KK$ is a field extension and $alpha in KK$ is an algebraic element over $FF$. Then
$ I = { p(x) in FF[x] : p(alpha) = 0 } $
is a nonzero ideal in $FF[x]$. Since $FF[x]$ is a principle ideal domain, there exists a unique monic polynomial $m_(alpha,FF) (x) in FF[x]$, such that $I = (m_(alpha,FF) (x))$.

#definition[
  The polynomial $m_(alpha,FF) (x)$ in the above is called the _minimal polynomial_ of $alpha$ over $FF$. If $FF$ is clear from the context, we also abbreviate this as $m_alpha (x)$.
]

#lemma[
  A monic polynomial $p(x) in FF[x]$ is a minimal polynomial of $alpha in KK$ if and only if
  + $p(alpha) = 0$, and
  + $p(x)$ is irreducible over $FF$.
]

#proof[
  / "$==>$": Suppose $p(x) = m_alpha (x)$. By definition, $p(alpha) = 0$ and $p(x)$ generates the ideal of polynomials vanishing at $alpha$. Suppose $p(x) = q_1(x) dot q_2(x)$. Then $p(alpha) = q_1(alpha) dot q_2(alpha)$. Without loss of generality, assume that $q_1(alpha) = 0$, that is $q_1(x) in (p(x))$, therefore $p(x) divides q_1(x)$. But also $q_1(x) divides p(x)$ by our assumption. Therefore $p(x)$ and $q_1(x)$ are associate in $FF[x]$, hence $q_2(x)$ is a unit.

  / "$<==$": Similarly to the above. #theoretic.qed()
]

Suppose $FF arrow.hook KK$ and $alpha in KK$ is algebraic over $FF$. Since $m_(alpha,FF) (x)$ is irreducible, the ideal $(m_(alpha,FF) (x))$ is maximal. Hence $FF[x] \/ (m_(alpha,FF) (x))$ is a field.

#proposition[
  In the context above, $FF[x] \/ (m_(alpha,FF) (x)) tilde.equiv FF (alpha)$.
]

#proof[
  Consider the evaluation homomorphism
  $ "ev"_alpha : FF[x] -> KK. $
  The image of $"ev"_alpha$ is $FF[alpha]$, the subring of $KK$ generated by $FF$ and $alpha$. But the image is also isomorphic to $FF[x] \/ (m_(alpha,FF) (x)) = FF[x] \/ ker "ev"_alpha$, which is a field.
]

#corollary[
  In the context above, $[FF(alpha) : FF] = deg m_(alpha,FF)$.
]

#proof[
  This follows from the general fact that, for a monic polynomial $p(x) = a_0 + dots + a_(n-1) x^(n-1) + x^n in FF[x]$, it holds that
  $ FF[x] \/ (f(x)) tilde.equiv { b_0 + b_1 x + dots + b_(n-1) x^(n-1) : b_0, dots, b_(n-1) in FF } tilde.equiv FF^n. $
]

Note that conversely, if $p(x) = a_0 + dots + a_(n-1) x^(n-1) + x^n in FF[x]$ is an irreducible polynomial, then $FF[x] \/ (m_(alpha,FF) (x))$ is a field extension of $FF$ of degree $n$. Furthermore, the element $x + (p(x)) in FF[x] \/ (p(x))$ is a zero of $p(x)$, and $p(x)$ is the minimal polynomial of the element $x + (p(x))$.

#lemma[
  Let $FF arrow.hook KK$ be a field extension, then $alpha in KK$ is algebraic over $FF$ if and only if $[FF(alpha) : FF] < oo$.
]

#proof[
  / "$==>$": Follows immediately from the previous corollary.

  / "$<==$": The elements $1, alpha, alpha^2, dots, alpha^n$ are linearly dependant over $FF$. Therefore there exist $s_0, s_1, dots, s_n in FF$, not all zero, such that $s_0 + s_1 alpha + dots + s_n alpha^n = 0$, therefore $alpha$ is algebraic over $FF$. #theoretic.qed()
]

#corollary[
  Suppose $FF arrow.hook KK$ and $alpha, beta in KK$ are algebraic over $FF$. Then $alpha plus.minus beta, alpha beta, 1/alpha$ (provided that $alpha eq.not 0$) are algebraic over $FF$.
]

#proof[
  By the previous lemma, it suffices to show that the respective generated extensions are of finite degree. The fields $FF(alpha plus.minus beta), FF(alpha beta)$ are subfields of $FF(alpha, beta)$. But the latter extension has finite degree, since
  $
    [FF(alpha, beta) : FF] = [FF(alpha, beta) : FF(alpha)] dot [FF(alpha) : FF] <= [FF(beta) : FF] dot [FF(alpha) : FF] < oo.
  $
  The final claim follows from the fact that $FF(alpha) = FF(frac(1, a, style: "skewed"))$.
]

#corollary[
  Suppose $FF arrow.hook KK$. Then the set of all algebraic elements of $KK$ is a sub-extension of $KK$, in other words it is a sub-field of $KK$ that is also an extension $FF$. This is called the _algebraic closure_ of $FF$ in $KK$.
]

#example[
  We want to determine the minimal polynomial of $sqrt(2) + sqrt(3)$ over $QQ$. We consider that we ultimately want something like $x = sqrt(2) + sqrt(3)$. Squaring yields $x^2 + 5 + 2 sqrt(6)$, or equivalently $x^2 - 5 = 2 sqrt(6)$. Squaring again yields $x^4 - 10x^2 + 1$. It remains to show that this polynomail, say $p(x)$, is minimal, which will be the case if we can show that it is irreducible over $QQ$.

  Since $p(x)$ is monic with integer coefficients, by Gauss' lemma it suffices to rule out factorizations over $ZZ$. Note that, by the rational root theorem, the only root candidates are $plus.minus 1$, and neither turn out to actually be roots. Hence there can be no linear factors.

  Suppose that
  $
    p(x) & = x^4 - 10x^2 + 1 \
         & =^? (x^2 + a x + b)(x^2 + c x + d) \
         & = x^4 + a x^3 + b x^2 + c x^3 + a c x^2 + b c x + d x^2 + a d x + b d \
         & = x^4 + (a + c) x^3 + (b + a c + d) x^2 + (a d + b c) x + b d
  $
  with $a, b, c, d in ZZ$. By comparing coefficients, we get
  #enum(
    numbering: "(i)",
    enum.item[$a+c=0$,],
    enum.item[$b + a c + d & = -10$,],
    enum.item[$a d + b c = 0$,],
    enum.item[$b d = 1$.],
  )
  From (i) we get $a = -c$, from (iii) we get $a (d - b) = 0$.
  - If $a = 0$, then $c = 0$ and from (ii) we get $d = -10 -b$. From (iv) we get
  $ 1 =^? b (-10 - b) = -10b - b^2 quad <==> quad b^2 + 10b - 1 = 0, $
  which yields $b = -5 plus.minus sqrt(96) = -5 plus.minus 2 sqrt(6) in.not QQ$.
  - If $d = b$, then from (iv) we get $1 = b^2$, thus $b = plus.minus 1$, and from (ii) we get $a^2 - 2b = 10$. The case $b=1$ yields $a^2 = 12$, while $b=1$ yields $a^2 = 8$, both of which are not perfect squares.
  Therefore we have shown that $p(x)$ is irreducible over $QQ$, and hence the minimal polynomial of $sqrt(2) + sqrt(3)$.
]
