#import "../preamble.typ": *

#lecture-date("03.09.2026")

= Fields

Throughout the semester, we will employ the following conventions:

+ Unless otherwise specified, all rings will be assumed to be unital and commutative.
+ A _ring homomorphism_ is a map of rings $phi : R -> S$, such that
  + $phi(x + y) = phi(x) + phi(y)$, for all $x, y in R$.
  + $phi(x dot y) = phi(x) dot phi(y)$, for all $x, y in R$.
  + $phi(1_(R)) = 1_(S)$

#definition[
  Let $R$ be a ring. An element $x in R$ is called a _unit_ or _invertible_, if there exists an element $y in R$ such that $x dot y = 1$.
]

The set of all units of $R$ form a group under multiplication and will be denoted $R^*$.

#example[
  + $ZZ^* = { -1, 1}$
  + $QQ^* = QQ without {0}$
  + For $n in NN$, it holds that $ZZ_n^* = { m in ZZ_n : gcd(m, n) = 1 }$.
]

#definition[
  A _field_ is a ring $K$ such that $K^* = K without {0}$.
]

#example[
  We recall the following fields:
  + $QQ subset.neq RR subset.neq CC$
  + $ZZ_p$, where $p in PP$.
]

#lemma[
  A ring $R$ is a field if and only if the only ideals of $R$ are ${0}$ and $R$.
]

#proof[
  Let $I subset.eq R$ be an ideal. If $I$ contains a unit then $I = R$.

  / "$==>$": Assume $R$ is a field. If $I subset.eq R$ is a non-zero, non-trivial ideal, then $I$ contains a unit, which implies $I = R$.

  / "$<==$": If $R$ is not a field, then there exists some non-zero, non-unit element $x in R$. But then the ideal $R x$ satisfies ${0} subset.neq R x subset.neq R$. #qed()
]

#corollary[
  A homomorphism of fields is always injective.
]

#proof[
  Let $phi : KK -> LL$ be a homomorphism of fields. Then $ker phi$ is an ideal in $K$. We have $1_KK in.not ker phi$, therefore $ker phi = { 0 }$ and $phi$ is injective.
]

== Field extensions

When constructing new fields, there are two main approaches:
+ The approach "from above", where we consider intersections of fields that satisfy our requirements of an extension, which we will discuss in the following.
+ The approach "from below", where we explicitly construct a new field based on roots of polynomials. We will discuss this approach in the next section.

#lemma[
  Suppose $KK$ is a field and ${ FF_alpha : alpha in I }$ is a family of subfields of $KK$. Then
  $ inter.big_(alpha in I) FF_alpha $
  is a subfield of $KK$.
]

#definition[
  Suppose $LL_0 subset.eq LL$ are fields and $alpha_1, alpha_2, dots in LL$. Then we define
  $ LL_0(alpha_1, alpha_2, ...) $
  as the intersection of all subfields of $LL$ that contain $LL_0$ and $alpha_1, alpha_2, dots$, and will be called the _extension_ of $LL_0$ generated by $alpha_1, alpha_2, dots$.
]

It is clear that such an extension is the smallest subfield of $LL$ that contains $LL_0$ and the elements $alpha_1, alpha_2, dots$.

#example[
  + Consider the fields $QQ subset.eq RR$, then one can show
    $ QQ(sqrt(2)) = { p + q sqrt(2) : p, q in QQ}. $
  + Since the element $1_QQ$ generates $QQ$ as a field, it follows that $QQ$ has no proper subfields, i.e. $QQ$ is a _primary field_.
  + The field $FF_p$ is a primary field for any $p in PP$.
]

#definition[
  Let $FF$ be a field. The _primary subfield_ of $FF$ is the subfield generated by the element $1_FF$.
]

#definition[
  Let $R$ be a ring, then its _characteristic_ is defined by
  $
    "char" R := cases(
      min { n in N : sum_(j=1)^n 1_R = 0}"," & "if such an" n "exists,",
      0"," & "otherwise."
    )
  $
]

#lemma[
  Let $FF$ be a field.
  + If $"char" FF = 0$, then the primary subfield of $FF$ is#footnote[We always mean "up to isomorphism".] $QQ$.
  + If $"char" FF = p in PP$, then the primary subfield of $FF$ is $FF_p$.
]

#lemma[
  Suppose $M subset.neq RR$ is a maximal ideal. Then the quotient $R \/ M$ is a field.
]

#remark[
  Suppose $KK$ is a field and consider $KK[x]$, the ring of polynomials in $x$ with coefficients in $KK$. Recall that $KK[x]$ is a principle ideal domain. A non-trivial ideal $(f(x))$ is maximal in $KK[x]$ if and only if $f(x)$ is an irreducible polynomial. In particular, $KK[x] \/ (f(x))$ is a field whenever $f(x)$ is irreducible over $KK$.

  Moreover, $KK[x] \/ (f(x))$ contains $KK$ as a subfield, via the homomorphisms
  $ KK arrow.hook KK[x] arrow KK[x] \/ (f(x)). $
  Therefore, for every irreducible $f(x)$ the field $KK[x] \/ (f(x))$ is a field extension of $KK$.

  Note that $f(x)$ being irreducible with $deg f > 1$ implies that $f(x)$ has no roots in $KK$. But $f(x)$ always has a root in $KK[x] \/ (f(x))$, because $f(x)$ is zero as an element of $KK[x] \/ (f(x))$.
]

The above demonstrates, roughly, that there are relationships:
$
          "Polynomials" quad & arrow.long.r.l quad "Field extensions" \
  "Properties of roots" quad & arrow.long.r.l quad "Symmetries of field extensions"
$
Practically, we want some criteria to determine if a polynomial is irreducible.

#remark[
  If $KK$ is a field and $p(x) in KK[x]$, $deg p > 1$ is a polynomial with a root in $KK$, then $p(x)$ is not irreducible. Indeed, for any $a in KK$ one can write
  $ p(x) = q(x) (x-a) + p(a) $
  for some polynomial $q(x) in KK[x]$. If $a$ is a root of $p(x)$, this demonstrates that $p(x)$ is not irreducible.

  Note that the converse fails: The polynomial $(x^2 + 1)^2$ has no roots in $RR$, yet is not irreducible.
]

#lemma[
  For a field $KK$, a polynomial $p(x) in KK[x]$ with $2 <= deg p <= 3$ is irreducible if and only if it has no roots in $KK$.
]

#lemma[Gauss][
  Suppose $p(x) = a_0 + a_1 x + dots + a_n x^n in ZZ[x]$ is _primitive_, that is $gcd(a_0, a_1, dots, a_n) = 1$. Then $p(x)$ is irreducible in $ZZ[x]$ if and only if it is irreducible in $QQ[x]$.
]

#lemma[Eisenstein's Criterion][
  Let $q(x) = a_0 + a_1 x + ... + a_n x^n in ZZ[x]$ and suppose there exists a prime $p in PP$ such that:
  + $p divides.not a_n$
  + $p divides a_0, dots, a_(n-1)$
  + $p^2 divides.not a_0$
  Then $q(x)$ is irreducible in $QQ[x]$.
]

#example[
  + The polynomial
    $ q(x) = 2x^3 + 6x^2 - 9x + 15 $
    satisfies Eisenstein's criterion with $p=3$.

  + The polynomial
    $ q(x) = x^2 + x + 1 $
    does not satisfy Eisenstein's criterion. Nevertheless, one can consider the transformation
    $ r(x) = q(x+1) = (x+1)^2 + (x+1) + 1 = x^2 + 3x + 3, $
    which does satisfy the criterion. Hence $q(x)$ is also irreducible.

    More generally, using the same method as above, one can show that for any prime $p in PP$, the polynomial
    $ q(x) = x^(p-1) + x^(p-2) + dots + 1 $
    is irreducible.
]

