name: Build

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
        steps:
            - uses: actions/checkout@v7
              with:
                  fetch-depth: 0
            - uses: oven-sh/setup-bun@v2
            - run: bun install
              working-directory: www
            - run: bun generate
              working-directory: www
            - run: bun run build
              working-directory: www
            - uses: actions/configure-pages@v6
            - uses: actions/upload-pages-artifact@v5
              with:
                  path: "www/dist"
            - id: deploy
              uses: actions/deploy-pages@v5
