name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: corepack enable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/www/.next/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: 'yarn'
          cache-dependency-path: www/yarn.lock

      - name: Install dependancies
        run: yarn install --frozen-lockfile
        working-directory: www

      - name: Build frontend
        run: yarn build
        working-directory: www

      - name: Copy documents
        run: yarn tsx scripts/copy-lecture-notes.ts
        working-directory: www

      - name: Add deployment files
        run: |
          echo 'lecturenotes.hornik.dev' > out/CNAME
          touch out/.nojekyll
          working-directory: www

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: www/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}